[package]
name = "magma-cipher"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magma = "0.8"
rand = "0.8"
hex-literal = "0.3"
safer-ffi = "0.0.10"